e_com/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm
app_name='core'

urlpatterns=[
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
]

e_com/e_com/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
#from core.views import index,contact

urlpatterns = [
    path('',include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/',include('item.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT )

e_com/item/urls.py
from django.urls import path
from . import views

app_name='item'
urlpatterns = [
    path('<int:pk>/',views.detail,name='detail'),
] 

e_com/core/models.py
from django.db import models

# Create your models here.

e_com/item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=200)

    class Meta:
        ordering=('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Item(models.Model):
    Category=models.ForeignKey(category,related_name='items',on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    description=models.TextField(blank=True,null=True)
    price=models.FloatField()
    image=models.ImageField(upload_to='item_images',blank=True,null=True)
    is_sold=models.BooleanField(default=False)
    created_by=models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

e_com/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

    email=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Enter email address',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

    password1=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

e_com/core/views.py
from django.shortcuts import render,redirect
from item.models import category,Item
from .forms import SignupForm

# Create your views here.
def index(request):
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=category.objects.all()

    return render(request,'core/index.html', {
        'categories' : categories,
        'items' : items,
    })

def contact(request):
    return render(request,'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
        
    else:
        form=SignupForm()

    return render(request , 'core/signup.html', {
        'form': form
    })

e_com/item/views.py
from django.shortcuts import render,get_object_or_404
from .models import Item
# Create your views here.
def detail(request,pk):
    item = get_object_or_404(Item , pk=pk)
    #related_items=Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
    return render(request,'item/detail.html',{
        'item' : item,
        #'related_items': related_items
    })

e_com/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}Document puddle{% endblock %}</title>
</head>
<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">VirtuMart</a>

        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-gray-500">New Item</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            <a href="{% url 'core:signup' %}" class="px-6 py-6 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign-up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-6 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>

        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
   <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">This site is te most trustworthy online shopping site</p>

        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>

        </div>
   </footer>
</body>
</html>

e_com/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}contact page{% endblock %}

{% block content %}
    <h1 class="text-3xl font-bold underline">contact page of the site</h1>
{% endblock %}

e_com/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}home page{% endblock %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items on sale</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="">
                            <img src="{{ item.image.url }}" class="rounded-t-xl object-fill w-full h-full">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">
                   
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} items</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

e_com/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

       
       <div class="mb-3">
        <label for="" class="inline-block mb-2">Username</label><br>
        {{ form.username }}
       </div>
       <!-- <div class="mb-3">
        <label for="" class="inline-block mb-2">Email</label><br>
        {{ form.email }} -->
       <!-- </div> -->
       <div class="mb-3">
        <label for="" class="inline-block mb-2">Password</label><br>
        {{ form.password }}
       </div>
       <!-- <div class="mb-3">
        <label for="" class="inline-block mb-2">Confirm password</label><br>
        {{ form.password2 }}
       </div> -->
       {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
       {% endif %}
        <button class="py-4 px-8 text-lg bg-gray-500 hover:bg-gray-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

e_com/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Signup</h1>

    <form method="post" action=".">
        {% csrf_token %}

       
       <div class="mb-3">
        <label for="" class="inline-block mb-2">Username</label><br>
        {{ form.username }}
       </div>
       <div class="mb-3">
        <label for="" class="inline-block mb-2">Email</label><br>
        {{ form.email }}
       </div>
       <div class="mb-3">
        <label for="" class="inline-block mb-2">Password</label><br>
        {{ form.password1 }}
       </div>
       <div class="mb-3">
        <label for="" class="inline-block mb-2">Confirm password</label><br>
        {{ form.password2 }}
       </div>
       {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
       {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

e_com/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl object-fill">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <h1 class="text-gray-500"><strong>Price: </strong>{{ item.price }}</h1>
        <h1 class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</h1>
        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description :</strong><br>
            {{ item.description}}
        </p>
        {% endif %}

        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-teal-700">Contact Seller</a>
    </div>
</div>

{% endblock %}